### ISSUE TITLE
Determine Patreon perks

### ISSUE THREAD

**Issue by CNace13** [ProjectRio/ProjectRio-web#47]

**Comment by jonslui** [comment]
1. Special label/icon on User Profile page?
2. Name in a list of patreons on a projectrio.online/patreons page?
3. Special Discord tag/emojis?

**Comment by jonslui** [comment]
QUESTIONS:

1. Will there be different tiers?

**Comment by CNace13** [comment]
Ideas:

More stats available to patrons. Maybe things that are tedious to calculate or intensive. Nothing fundamental though, just frill stats.

Patrons vote on new stats we are considering.

Unlimited communities? Should we call this to a certain amount now?

**Comment by jonslui** [comment]
Patreon Tournaments/Games
