### ISSUE TITLE
Rio-UI Alpha

### ISSUE THREAD

**Issue by sleepywitch** [ProjectRio/ProjectRio-web#75]
An alpha for the RIO-UI should be like an initial sketch that shows off the features we plan to have. Base functionality for all primary features should be implemented, but advanced functionality and advance features are not required. The styling of the website should be a rough sketch too. It should be presentable, but the perfect color scheme and styling does not need to be there.

Current plans for the Alpha:
> Hosting figured out
> Basic Batting Stats for Player, Leaderboard, and All Characters
> Basic Pitching Stats for Player, Leaderboard, and All Characters
> Player Records? Basically the Player Leaderboard from Project Figma
> Character Data
> Design Document detailing this

**Comment by jonslui** [comment]
Closing this epic for clean up, if you want to message us to talk more please feel free.
